import { type HTMLAttributes } from "react";
import type { MorphAsset } from "./morph/types";
import { type MorphIconPreset, type MorphIconState } from "./runtime/morph";
export { cloneAsset, getPresetById, morphPresets } from "./morph/presets";
export type { MorphAsset, MorphLayer, MorphLayerMode, MorphLoadingDesign, } from "./morph/types";
export type { MorphIconPreset, MorphIconState } from "./runtime/morph";
export type MorphIconProps = Omit<HTMLAttributes<HTMLSpanElement>, "children" | "color"> & {
    active?: boolean;
    asset?: MorphAsset;
    color?: string;
    duration?: number;
    preset?: MorphIconPreset;
    progress?: number;
    size?: number;
    state?: MorphIconState;
    strokeWidth?: number;
    title?: string;
};
export declare function MorphIcon({ active, asset, color, duration, preset, progress, size, state, strokeWidth, style, title, ...spanProps }: MorphIconProps): import("react").JSX.Element;
export declare function getMorphIconPreset(id: string): MorphAsset;
